// <auto-generated />
using System;
using Data_InfoTransito.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_InfoTransito.Migrations
{
    [DbContext(typeof(InfoTransitoDbContext))]
    partial class InfoTransitoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Business_InfoTransito.Models.Events.Sinistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroundType")
                        .HasColumnType("int");

                    b.Property<bool>("InjuredPeople")
                        .HasColumnType("bit");

                    b.Property<int>("RoadPavementType")
                        .HasColumnType("int");

                    b.Property<int>("RoadType")
                        .HasColumnType("int");

                    b.Property<string>("SinistroDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SinistroType")
                        .HasColumnType("int");

                    b.Property<int>("Weather")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sinistros", (string)null);
                });

            modelBuilder.Entity("Business_InfoTransito.Models.Events.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CarLisencePlate")
                        .IsRequired()
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ManufacturingYear")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("PersonId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SinistroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypeVehicle")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SinistroId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("Business_InfoTransito.Models.Location.PersonAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Complement")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("PersonsAddresses", (string)null);
                });

            modelBuilder.Entity("Business_InfoTransito.Models.Location.SinistroAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Complement")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("SinistroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SinistroId")
                        .IsUnique();

                    b.ToTable("SinistrosAddresses", (string)null);
                });

            modelBuilder.Entity("Business_InfoTransito.Models.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<bool?>("Gender")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.Property<Guid>("SinistroID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SinistroID");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("Business_InfoTransito.Models.Events.Vehicle", b =>
                {
                    b.HasOne("Business_InfoTransito.Models.Events.Sinistro", "Sinistro")
                        .WithMany("VehiclesEnvolved")
                        .HasForeignKey("SinistroId")
                        .IsRequired();

                    b.Navigation("Sinistro");
                });

            modelBuilder.Entity("Business_InfoTransito.Models.Location.PersonAddress", b =>
                {
                    b.HasOne("Business_InfoTransito.Models.People.Person", "person")
                        .WithOne("Address")
                        .HasForeignKey("Business_InfoTransito.Models.Location.PersonAddress", "PersonId")
                        .IsRequired();

                    b.Navigation("person");
                });

            modelBuilder.Entity("Business_InfoTransito.Models.Location.SinistroAddress", b =>
                {
                    b.HasOne("Business_InfoTransito.Models.Events.Sinistro", "SinistroRegister")
                        .WithOne("SinistroAddress")
                        .HasForeignKey("Business_InfoTransito.Models.Location.SinistroAddress", "SinistroId")
                        .IsRequired();

                    b.Navigation("SinistroRegister");
                });

            modelBuilder.Entity("Business_InfoTransito.Models.People.Person", b =>
                {
                    b.HasOne("Business_InfoTransito.Models.Events.Sinistro", "Sinistro")
                        .WithMany("PeopleEnvolved")
                        .HasForeignKey("SinistroID")
                        .IsRequired();

                    b.Navigation("Sinistro");
                });

            modelBuilder.Entity("Business_InfoTransito.Models.Events.Sinistro", b =>
                {
                    b.Navigation("PeopleEnvolved");

                    b.Navigation("SinistroAddress");

                    b.Navigation("VehiclesEnvolved");
                });

            modelBuilder.Entity("Business_InfoTransito.Models.People.Person", b =>
                {
                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
